syntax = "proto3";

import "packet.proto";
import "shared.proto";

package bundle;

// A bundle is a sequence of transactions that executes all or nothing.
message Bundle {
  shared.Header header = 2;
  repeated packet.Packet packets = 3;
  // Indices into packets for transactions that may be dropped from the bundle.
  // Every index must refer to an existing packet, or the bundle will be rejected.
  repeated uint32 dropping_indices = 4;
  // If set, the bundle may only land in this slot.
  optional uint64 slot = 5;
  // Accounts that this bundle is targeting. Each account must be 32 bytes, max
  // 16 accounts can be specified. The builder will consider the bundle after
  // transactions that write to these accounts.
  repeated bytes target_accounts = 6;
}
